---
- name: install required packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
   - python-pycurl
   - python-apt

- name: fetch Sysdig key
  apt_key:
    url: "{{ sysdig_repokey }}"
    state: present

- name: fetch Sysdig repo
  get_url:
    url: "{{ sysdig_url_apt }}"
    dest: "{{ sysdig_repo_apt }}"
    owner: root
    group: root
    mode: 0644

- name: install linux headers
  apt:
    pkg: "linux-headers-{{ ansible_kernel }}"
    update_cache:yes
    state: latest

- name: install sysdig
  apt:
    pkg: "{{ sysdig_package }}"
    update_cache: yes
    state: present
